# Generated by Django 5.1.3 on 2024-11-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonMatchingTable",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gender", "Gender"),
                            ("age", "Age"),
                            ("caste", "Caste"),
                            ("religion", "Religion"),
                            ("profession", "Profession"),
                            ("income", "Income"),
                            ("education", "Education"),
                            ("height", "Height"),
                            ("weight", "Weight"),
                            ("location", "Location"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
