# Generated by Django 5.1.3 on 2024-11-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_commonmatching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonmatchingtable",
            name="type",
            field=models.CharField(
                choices=[
                    ("gender", "Gender"),
                    ("age", "Age"),
                    ("caste", "Caste"),
                    ("religion", "Religion"),
                    ("profession", "Profession"),
                    ("income", "Income"),
                    ("education", "Education"),
                    ("height", "Height"),
                    ("weight", "Weight"),
                    ("location", "Location"),
                    ("language", "Language"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
