# Generated by Django 5.1.3 on 2024-11-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_commonmatching", "0002_alter_commonmatchingtable_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=50, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_commonmatching.commonmatchingtable",
                    ),
                ),
            ],
        ),
    ]
