# Generated by Django 5.1.3 on 2024-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_commonmatching", "0004_alter_commonmatchingtable_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonmatchingtable",
            name="type",
            field=models.CharField(
                choices=[
                    ("gender", "Gender"),
                    ("caste", "Caste"),
                    ("religion", "Religion"),
                    ("profession", "Profession"),
                    ("education", "Education"),
                    ("location", "Location"),
                    ("language", "Language"),
                    ("marital_status", "Marital_status"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
