# Generated by Django 5.1.3 on 2024-11-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_commonmatching", "0005_alter_commonmatchingtable_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastertable",
            name="value",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
