# Generated by Django 5.1.3 on 2024-11-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gender", models.CharField(blank=True, max_length=50, null=True)),
                ("Date_of_Birth", models.DateField(blank=True, null=True)),
                ("Age", models.IntegerField(blank=True, null=True)),
                ("Height", models.IntegerField(blank=True, null=True)),
                ("Weight", models.IntegerField(blank=True, null=True)),
                ("Religion", models.CharField(blank=True, max_length=50, null=True)),
                ("Caste", models.CharField(blank=True, max_length=50, null=True)),
                ("Income", models.IntegerField(blank=True, null=True)),
                ("Profession", models.CharField(blank=True, max_length=50, null=True)),
                ("Education", models.CharField(blank=True, max_length=50, null=True)),
                ("Bio", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Marial_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("Address", models.CharField(blank=True, max_length=200, null=True)),
                ("Language", models.CharField(blank=True, max_length=50, null=True)),
                ("Profile_img", models.ImageField(upload_to="profile_img")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
