# Generated by Django 5.1.3 on 2024-11-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Marial_status",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
