# Generated by Django 5.1.3 on 2024-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_userprofile", "0002_alter_userprofile_marial_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Marial_status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
