# Generated by Django 5.1.3 on 2024-11-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_userprofile", "0003_alter_userprofile_marial_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="Address",
            new_name="Location",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="Marial_status",
            new_name="Marital_status",
        ),
    ]
