# Generated by Django 5.1.3 on 2024-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_userprofile", "0004_rename_address_userprofile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
