# Generated by Django 5.1.3 on 2024-11-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_notification",
            "0004_rename_notification_notification_notification_content_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
