# Generated by Django 5.1.3 on 2024-11-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_message", "0003_alter_message_receiver_id_alter_message_sender_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("message", "Message"), ("request", "Request")],
                default="message",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("unread", "Unread"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="unread",
                max_length=10,
            ),
        ),
    ]
