# Generated by Django 5.1.3 on 2024-11-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscription", "0001_initial"),
        ("app_user", "0002_customuser_is_admin_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription_plan",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_subscription.subscription",
            ),
        ),
    ]
