# Generated by Django 5.1.3 on 2024-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
