# Generated by Django 5.1.3 on 2024-11-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscription", "0001_initial"),
        ("app_user", "0003_alter_customuser_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_subscription.subscription",
            ),
        ),
    ]
