# Generated by Django 5.1.3 on 2024-11-15 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_matching",
            "0002_alter_matching_match_score_alter_matching_status_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matching",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="matching",
            name="match_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matching",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="matching",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="matching",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
