# Generated by Django 5.1.3 on 2024-11-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_matching", "0003_alter_matching_unique_together_and_more"),
    ]

    operations = []
