# Generated by Django 5.1.3 on 2024-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_subscription", "0002_remove_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="status",
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(max_length=10),
        ),
    ]
