# Generated by Django 5.1.3 on 2024-11-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_preference", "0002_rename_age_preference_age_max_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="Age_max",
            new_name="Age",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Height_max",
            new_name="Height",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Income_max",
            new_name="Income",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Weight_max",
            new_name="Weight",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Age_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Height_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Income_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Weight_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Education",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Location",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Profession",
        ),
        migrations.AddField(
            model_name="preference",
            name="Education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
