# Generated by Django 5.1.3 on 2024-11-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_commonmatching", "0005_alter_commonmatchingtable_type"),
        ("app_preference", "0003_rename_age_max_preference_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="Age",
            new_name="age_max",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Height",
            new_name="height_max",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Income",
            new_name="income_max",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="Weight",
            new_name="weight_max",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Caste",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Education",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Gender",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Location",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Profession",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="Religion",
        ),
        migrations.AddField(
            model_name="preference",
            name="age_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="height_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="income_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="language",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "language"},
                related_name="preferences_language",
                to="app_commonmatching.mastertable",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="weight_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="caste",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "caste"},
                related_name="preferences_caste",
                to="app_commonmatching.mastertable",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "education"},
                related_name="preferences_education",
                to="app_commonmatching.mastertable",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "location"},
                related_name="preferences_location",
                to="app_commonmatching.mastertable",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="profession",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "profession"},
                related_name="preferences_profession",
                to="app_commonmatching.mastertable",
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="religion",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__type": "religion"},
                related_name="preferences_religion",
                to="app_commonmatching.mastertable",
            ),
        ),
    ]
