# Generated by Django 5.1.3 on 2024-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_preference", "0004_rename_age_preference_age_max_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preference",
            old_name="age_max",
            new_name="Age",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="height_max",
            new_name="Height",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="income_max",
            new_name="Income",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="weight_max",
            new_name="Weight",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="age_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="caste",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="education",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="height_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="income_min",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="language",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="location",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="religion",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="weight_min",
        ),
        migrations.AddField(
            model_name="preference",
            name="Gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Caste",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="Religion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
