# Generated by Django 5.1.3 on 2024-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_preference",
            "0006_preference_language_preference_marital_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="Caste",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="Religion",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
