# Generated by Django 5.1.3 on 2024-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_preference", "0007_alter_preference_caste_alter_preference_religion"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
